# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r: release

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libhdf5-dev; fi

install:
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - R CMD check *tar.gz
