# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: release

os:
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libhdf5-dev; fi

addons:
  apt:
    update: true
    packages:
       -   x11proto-xf86vidmode-dev
       -   xvfb
       -   libxxf86vm-dev

before_script:
  - "export DISPLAY=:99.0"

r_packages:
  - covr
  - testthat

r_github_packages:
  - asgr/ProSpect

script:
  - R CMD build .
  - xvfb-run R CMD check *tar.gz --as-cran

after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
  - cat "/Users/travis/build/kateharborne/SimSpin/SimSpin.Rcheck/00check.log"
