# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r: release

os:
  - linux
  - osx

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libhdf5-dev; fi

r_github_packages: asgr/ProSpect

script:
  - R CMD build .
  - R CMD check --as-cran *tar.gz

# for codecov
r_packages:
  - covr

# only report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
  - cat  "/Users/travis/build/kateharborne/SimSpin/SimSpin.Rcheck/00check.log"
