# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: release

os:
  - linux

warnings_are_errors: false

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libhdf5-dev; fi

addons:
  apt:
    update: true
    packages:
       -   x11proto-xf86vidmode-dev
       -   xvfb
       -   libxxf86vm-dev

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

r_packages:
  - covr
  - testthat

r_github_packages:
  - asgr/ProSpect

script:
  - R CMD build . --compact-vignettes=gs+qpdf
  - xvfb-run R CMD check *tar.gz --as-cran

after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
  - cat "/Users/travis/build/kateharborne/SimSpin/SimSpin.Rcheck/00check.log"
